/**
 * Generated by scripts/generate-brand.ts. Do not edit by hand.
 *
 * The letterforms and bottle silhouettes the application draws inline, so they
 * take the current theme's colours. The same geometry is written out as static
 * files for the installed icon, where no theme is available.
 */

/** A stroked shape carries its width; the rest are filled. */
export type BrandShape = { d: string; stroke?: number };

export const wordmarkBox = {
  height: 142,
  top: -42,
  width: 566,
} as const;

export const wordmarkShapes: readonly BrandShape[] = [
  { d: "M 0 0 L 50 100 L 100 0 L 70.93 0 L 50 41.86 L 29.07 0 Z" },
  { d: "M 121 50 a 37 37 0 1 0 74 0 a 37 37 0 1 0 -74 0", stroke: 26 },
  { d: "M 182 0 h 26 v 100 h -26 Z" },
  { d: "M 229 50 a 37 37 0 1 0 74 0 a 37 37 0 1 0 -74 0", stroke: 26 },
  { d: "M 290 -42 h 26 v 142 h -26 Z" },
  { d: "M 411 50 A 37 37 0 1 0 406.67 67.37", stroke: 26 },
  { d: "M 334 38.95 h 90 v 22.1 h -90 Z" },
  { d: "M 432 0 L 482 100 L 532 0 L 502.93 0 L 482 41.86 L 461.07 0 Z" },
  { d: "M 540 0 h 26 v 100 h -26 Z" },
  { d: "M 536 -25 a 17 17 0 1 0 34 0 a 17 17 0 1 0 -34 0" },
];

export const monogramBox = {
  height: 142,
  top: -42,
  width: 316,
} as const;

export const monogramShapes: readonly BrandShape[] = [
  { d: "M 0 0 L 50 100 L 100 0 L 70.93 0 L 50 41.86 L 29.07 0 Z" },
  { d: "M 121 50 a 37 37 0 1 0 74 0 a 37 37 0 1 0 -74 0", stroke: 26 },
  { d: "M 182 -42 h 26 v 142 h -26 Z" },
  { d: "M 216 0 L 266 100 L 316 0 L 286.93 0 L 266 41.86 L 245.07 0 Z" },
];

/** Seven bottles on a common baseline, in a 1200 x 900 box. */
export const bottleRow = {
  /** Left edge of the first bottle. */
  start: 169.68,
  /** Width of the whole row, which is also the pitch for repeating it. */
  span: 860.64,
} as const;

/** Where the wordmark sits over that row. */
export const lockupWordmark = {
  baseline: 700,
  centre: 600,
  width: 820,
} as const;

export const bottleRowPaths: readonly string[] = [
  "M 212.71 239.13 Q 212.71 232 219.84 232 H 251.52 Q 258.65 232 258.65 239.13 V 249.78 H 255.48 V 390.18 C 255.48 436.61 301.68 417.14 301.68 465.06 V 690.76 Q 301.68 700 292.44 700 H 178.92 Q 169.68 700 169.68 690.76 V 465.06 C 169.68 417.14 215.88 436.61 215.88 390.18 V 249.78 H 212.71 Z",
  "M 334.15 207.93 Q 334.15 200.8 341.28 200.8 H 372.96 Q 380.09 200.8 380.09 207.93 V 219.77 H 376.92 V 369.53 C 376.92 419.05 423.12 398.28 423.12 449.4 V 690.76 Q 423.12 700 413.88 700 H 300.36 Q 291.12 700 291.12 690.76 V 449.4 C 291.12 398.28 337.32 419.05 337.32 369.53 V 219.77 H 334.15 Z",
  "M 455.59 265.13 Q 455.59 258 462.72 258 H 494.4 Q 501.53 258 501.53 265.13 V 274.8 H 498.36 V 407.4 C 498.36 451.24 544.56 432.86 544.56 478.12 V 690.76 Q 544.56 700 535.32 700 H 421.8 Q 412.56 700 412.56 690.76 V 478.12 C 412.56 432.86 458.76 451.24 458.76 407.4 V 274.8 H 455.59 Z",
  "M 577.03 187.13 Q 577.03 180 584.16 180 H 615.84 Q 622.97 180 622.97 187.13 V 199.76 H 619.8 V 355.76 C 619.8 407.34 666 385.71 666 438.96 V 690.76 Q 666 700 656.76 700 H 543.24 Q 534 700 534 690.76 V 438.96 C 534 385.71 580.2 407.34 580.2 355.76 V 199.76 H 577.03 Z",
  "M 698.47 306.73 Q 698.47 299.6 705.6 299.6 H 737.28 Q 744.41 299.6 744.41 306.73 V 314.82 H 741.24 V 434.94 C 741.24 474.65 787.44 458 787.44 499 V 690.76 Q 787.44 700 778.2 700 H 664.68 Q 655.44 700 655.44 690.76 V 499 C 655.44 458 701.64 474.65 701.64 434.94 V 314.82 H 698.47 Z",
  "M 819.91 218.33 Q 819.91 211.2 827.04 211.2 H 858.72 Q 865.85 211.2 865.85 218.33 V 229.77 H 862.68 V 376.41 C 862.68 424.9 908.88 404.57 908.88 454.62 V 690.76 Q 908.88 700 899.64 700 H 786.12 Q 776.88 700 776.88 690.76 V 454.62 C 776.88 404.57 823.08 424.9 823.08 376.41 V 229.77 H 819.91 Z",
  "M 941.35 285.93 Q 941.35 278.8 948.48 278.8 H 980.16 Q 987.29 278.8 987.29 285.93 V 294.81 H 984.12 V 421.17 C 984.12 462.95 1030.32 445.43 1030.32 488.56 V 690.76 Q 1030.32 700 1021.08 700 H 907.56 Q 898.32 700 898.32 690.76 V 488.56 C 898.32 445.43 944.52 462.95 944.52 421.17 V 294.81 H 941.35 Z",
];
